AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Ingest logs from custom source into AWS Security Lake"
Globals:
  Function:
    Timeout: 3

Resources:
  SecurityLakeCustomLogsIngestionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: security-lake-custom-source-ingestion-lambda/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Role: <your IAM role>
      MemorySize: 1024
      Environment:
        Variables:
          ConfigurationFile: "s3://<your-s3-path>/log-schema-config.json"
      Architectures:
        - arm64
      Events:
        KinesisEvents:
          Type: Kinesis # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Stream: <your kinesis data stream>
            StartingPosition: TRIM_HORIZON
            BatchSize: 10000
            TumblingWindowInSeconds: 10
            

Outputs:
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SecurityLakeCustomLogsIngestionFunction:
    Description: "Ingest logs from custom source into AWS Security Lake"
    Value: !GetAtt SecurityLakeCustomLogsIngestionFunction.Arn
